####################################################################################
# docker-compose file for nginx proxy manager, to front guacamole
# created by waal70 02-10-2021
#
# Check: https://nginxproxymanager.com/guide/#project-goal
# ####################################################################################
#
# What does this file do?
#
# docker-compose up -d
#  - Create and run a container for nginx proxy manager - the web UI for nginx
#  - Create and run a MySQL (mariadb) database, using the aria storage provider
#  - Prepare some volumes, among others for letsencrypt support
#
# The initial login to the webinterface (hosted on port 81) is:
#
#   Email:    admin@example.com
#   Password: changeme
#   
# You will be asked to change this after initial login.
# Once up and running, use the following hints to configure a reverse proxy:
# use nginx proxy manager to create new proxy host
#
# set block common exploits
# set websockets support
# optionally add access list
# 
# forward to guac:8080 (this is the instance that is created in the main yaml)
#
# in Custom Locations
# Add /
# forward to guac:8080
# press the options wheel and add in the custom config, to have it map to the root:
#location / {
# proxy_pass http://guac:8080/guacamole/;
# proxy_redirect off;
# proxy_buffering off;
# proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
# proxy_set_header Upgrade $http_upgrade;
# proxy_set_header Connection $http_connection;
# proxy_cookie_path /guacamole/ /;
# access_log off;
# }
 
# in SSL tab request new certificate from letsencrypt
# Force SSL, HSTS, HTTP/2
# 
#
# version            date              comment
# 1.0                2021-10-01        initial release
####################################################################################
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql

